# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('crown_width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='treesample',
            name='treespecies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TreeSpecies'),
        ),
    ]
